Techservices/Controllers/CustomerController.cs
using AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using Techservices.Models;

namespace Techservices.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerRepository repo;

        public CustomerController(ICustomerRepository repo)
        {


            this.repo = repo;
        }

        [Authorize]
        public IActionResult Cxinfo()
        {

            var customer = repo.GetInfocustomers();
            return View(customer);
        }

    



        public IActionResult InsertCustomer()
        {

            var clients = repo.AssingCustomer();
            return View(clients);
        }



        public IActionResult InsertCustomerToDatabase(infocustomer customerToInsert)
        {
            repo.createCustomer(customerToInsert);

            return RedirectToAction("Cxinfo");
        }

        //public IActionResult customerupdate()
        //{
        //    infocustomer customer = (infocustomer)repo.GetInfocustomers();

        //    if (customer == null)
        //    {
        //        return View("customerNotFound");
        //    }

        //    return View(customer);
        //}


        //public IActionResult UpdatecustomerToDatabase(infocustomer customer) 
        //{ 

        //    repo.UpdateCustomer(customer);
        //    return RedirectToAction("Customer", new { customer = customer });


        //}

        public IActionResult deletecustomer(infocustomer customer)
        {
            repo.deleteCustomer(customer);
            return RedirectToAction("Cxinfo");

        }



    }
}

Techservices/Views/Customer/Cxinfo.cshtml
@model IEnumerable<infocustomer>

<h2 class="cx-2">Clients Dashboard</h2>



<div style="display: block">
    <a  href="~/Customer/InsertCustomer/" class="btn btn-primary">Create a New Client</a>
</div>

<table class="table">
    <tr>
        <th>ID </th>
        <th>Name</th>
        <th>Last Name</th>
        <th>Address</th>
        <th>Phone</th>
        <th>Service Date</th>
        <th>Device</th>
        <th>Comments</th>
     

    </tr>
    @foreach (var clients in Model)
     {
        <tr>
                <td>@clients.idcustomers</td>
                <td>@clients.name</td>
                <td>@clients.lastname</td>
                <td>@clients.address</td>
                <td>@clients.phone</td>
                <td>@clients.servicedate</td>
                <td>@clients.device</td>
                <td>@clients.comments</td>
            </tr>

    }

</table>

Techservices/Views/Customer/InsertCustomer.cshtml
@model infocustomer
<h2 class="cx-1">Add New Client</h2>

@using (Html.BeginForm("InsertCustomerToDatabase", "Customer", "Post"))
{

   // <label asp-for="idcustomers" class="control-label">ID</label>
    //<input type="number" name="idcustomers" class="form-control" />
   
    <label asp-for="name" class="control-label">Name</label>
    <input type="text" name="name" class="form-control"  required/>
    <span asp-validation-for="name"></span>

    <label asp-for="lastname" class="control-label">Last Name</label>
    <input type="text" name="lastname" class="form-control" required />

    <label asp-for="address" class="control-label">Address</label>
    <input type="text" name="address" class="form-control" required/>

    <label asp-for="phone" class="control-label">Phone</label>
    <input type="text" name="phone" class="form-control" required />

    <label asp-for="servicedate" class="control-label">Service Date</label>
    <input type="datetime" name="servicedate" class="form-control"/>

    <label asp-for="device" class="control-label">Device</label>
    <input type="text" name="device" class="form-control" required />

    <label asp-for="comments" class="control-label">Comments</label>
    <input type="text" name="comments" class="form-control"  required/>

       


    <input type="submit" value="Create Customer" class="btn btn-primary" />
}